Fix build with older protobuffer
Patch grpc-gateway dependency in Debian to fix build failure:

    # github.com/pingcap/kvproto/pkg/configpb
    src/github.com/pingcap/kvproto/pkg/configpb/configpb.pb.gw.go:45:44: cannot use &protoReq (value of type *GetRequest) as "google.golang.org/protobuf/proto".Message value in argument to runtime.PopulateQueryParameters: *GetRequest does not implement protoreflect.ProtoMessage (missing method ProtoReflect)
    src/github.com/pingcap/kvproto/pkg/configpb/configpb.pb.gw.go:58:44: cannot use &protoReq (value of type *GetRequest) as "google.golang.org/protobuf/proto".Message value in argument to runtime.PopulateQueryParameters: *GetRequest does not implement protoreflect.ProtoMessage (missing method ProtoReflect)
    src/github.com/pingcap/kvproto/pkg/configpb/configpb.pb.gw.go:112:44: cannot use &protoReq (value of type *DeleteRequest) as "google.golang.org/protobuf/proto".Message value in argument to runtime.PopulateQueryParameters: *DeleteRequest does not implement protoreflect.ProtoMessage (missing method ProtoReflect)
    src/github.com/pingcap/kvproto/pkg/configpb/configpb.pb.gw.go:125:44: cannot use &protoReq (value of type *DeleteRequest) as "google.golang.org/protobuf/proto".Message value in argument to runtime.PopulateQueryParameters: *DeleteRequest does not implement protoreflect.ProtoMessage (missing method ProtoReflect)
    src/github.com/pingcap/kvproto/pkg/configpb/configpb.pb.gw.go:304:107: too many arguments in call to runtime.NewPattern
           have (number, []int, []string, string, unknown type)
           want (int, []int, []string, string)
    src/github.com/pingcap/kvproto/pkg/configpb/configpb.pb.gw.go:304:115: undefined: runtime.AssumeColonVerbOpt
    src/github.com/pingcap/kvproto/pkg/configpb/configpb.pb.gw.go:306:110: too many arguments in call to runtime.NewPattern
       have (number, []int, []string, string, unknown type)
           want (int, []int, []string, string)
    src/github.com/pingcap/kvproto/pkg/configpb/configpb.pb.gw.go:306:118: undefined: runtime.AssumeColonVerbOpt
    src/github.com/pingcap/kvproto/pkg/configpb/configpb.pb.gw.go:308:110: too many arguments in call to runtime.NewPattern
           have (number, []int, []string, string, unknown type)
           want (int, []int, []string, string)
    src/github.com/pingcap/kvproto/pkg/configpb/configpb.pb.gw.go:308:118: undefined: runtime.AssumeColonVerbOpt
    src/github.com/pingcap/kvproto/pkg/configpb/configpb.pb.gw.go:125:44: too m

This can be dropped once Debian has upgraded to newer protobuffer libraries.